// <auto-generated />
using System;
using DiaryPortfolio.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryPortfolio.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260404121225_MakeFileModelSelectionIdNullable")]
    partial class MakeFileModelSelectionIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.CollectionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ConditionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AvailableTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.CustomUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PortfolioProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioProfileId");

                    b.ToTable("CustomUrls");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.DiaryProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DiaryProfile");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.EducationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Achievement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EducationFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EducationTierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PortfolioProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SelectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EducationFileId");

                    b.HasIndex("EducationTierId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PortfolioProfileId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ExperienceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PortfolioProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("PortfolioProfileId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.FileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SelectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SelectionId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.LocationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.MediaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LocationModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MediaStatusSelectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MediaTypeSelectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("LocationModelId");

                    b.HasIndex("MediaStatusSelectionId");

                    b.HasIndex("MediaTypeSelectionId");

                    b.HasIndex("SpaceId");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.PhotoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<Guid?>("MediaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProjectModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("ProjectModelId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.PortfolioProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProfilePhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResumeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProfilePhotoId");

                    b.HasIndex("ResumeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PortfolioProfile");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ProjectModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PortfolioProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProjectFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioProfileId");

                    b.HasIndex("ProjectFileId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ResumeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResumeFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResumeTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResumeFileId");

                    b.HasIndex("ResumeTemplateId");

                    b.ToTable("Resume");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ResumeTemplateModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResumeTemplate");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.SelectionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Selection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Selections");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.SkillModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PortfolioProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SelectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SkillLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioProfileId");

                    b.HasIndex("SkillLevelId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.SpaceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DiaryProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DiaryProfileId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Spaces");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.TypeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.VideoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProjectModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("ProjectModelId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ConditionModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.MediaModel", "MediaModel")
                        .WithOne("ConditionModel")
                        .HasForeignKey("DiaryPortfolio.Domain.Entities.ConditionModel", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaModel");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.CustomUrl", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.PortfolioProfile", "PortfolioProfile")
                        .WithMany()
                        .HasForeignKey("PortfolioProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioProfile");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.DiaryProfile", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.UserModel", "User")
                        .WithOne("DiaryProfile")
                        .HasForeignKey("DiaryPortfolio.Domain.Entities.DiaryProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.EducationModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.FileModel", "EducationFile")
                        .WithMany()
                        .HasForeignKey("EducationFileId");

                    b.HasOne("DiaryPortfolio.Domain.Entities.SelectionModel", "EducationTier")
                        .WithMany()
                        .HasForeignKey("EducationTierId");

                    b.HasOne("DiaryPortfolio.Domain.Entities.LocationModel", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.PortfolioProfile", "PortfolioProfile")
                        .WithMany()
                        .HasForeignKey("PortfolioProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationFile");

                    b.Navigation("EducationTier");

                    b.Navigation("Location");

                    b.Navigation("PortfolioProfile");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ExperienceModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.LocationModel", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.PortfolioProfile", "PortfolioProfile")
                        .WithMany()
                        .HasForeignKey("PortfolioProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("PortfolioProfile");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.FileModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.SelectionModel", "Selection")
                        .WithMany()
                        .HasForeignKey("SelectionId");

                    b.Navigation("Selection");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.MediaModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.CollectionModel", "CollectionModel")
                        .WithMany("MediaModels")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiaryPortfolio.Domain.Entities.LocationModel", "LocationModel")
                        .WithMany()
                        .HasForeignKey("LocationModelId");

                    b.HasOne("DiaryPortfolio.Domain.Entities.SelectionModel", "SelectionMediaStatusModel")
                        .WithMany()
                        .HasForeignKey("MediaStatusSelectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.SelectionModel", "SelectionMediaTypeModel")
                        .WithMany()
                        .HasForeignKey("MediaTypeSelectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.SpaceModel", "SpaceModel")
                        .WithMany("MediaModels")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionModel");

                    b.Navigation("LocationModel");

                    b.Navigation("SelectionMediaStatusModel");

                    b.Navigation("SelectionMediaTypeModel");

                    b.Navigation("SpaceModel");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.PhotoModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.MediaModel", "MediaModel")
                        .WithMany("PhotoModels")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DiaryPortfolio.Domain.Entities.ProjectModel", null)
                        .WithMany("Photos")
                        .HasForeignKey("ProjectModelId");

                    b.Navigation("MediaModel");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.PortfolioProfile", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.LocationModel", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("DiaryPortfolio.Domain.Entities.PhotoModel", "ProfilePhoto")
                        .WithMany()
                        .HasForeignKey("ProfilePhotoId");

                    b.HasOne("DiaryPortfolio.Domain.Entities.ResumeModel", "Resume")
                        .WithMany()
                        .HasForeignKey("ResumeId");

                    b.HasOne("DiaryPortfolio.Domain.Entities.UserModel", "User")
                        .WithOne("PortfolioProfile")
                        .HasForeignKey("DiaryPortfolio.Domain.Entities.PortfolioProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("ProfilePhoto");

                    b.Navigation("Resume");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ProjectModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.PortfolioProfile", "PortfolioProfile")
                        .WithMany()
                        .HasForeignKey("PortfolioProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.FileModel", "ProjectFile")
                        .WithMany()
                        .HasForeignKey("ProjectFileId");

                    b.Navigation("PortfolioProfile");

                    b.Navigation("ProjectFile");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ResumeModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.FileModel", "ResumeFile")
                        .WithMany()
                        .HasForeignKey("ResumeFileId");

                    b.HasOne("DiaryPortfolio.Domain.Entities.ResumeTemplateModel", "ResumeTemplate")
                        .WithMany()
                        .HasForeignKey("ResumeTemplateId");

                    b.Navigation("ResumeFile");

                    b.Navigation("ResumeTemplate");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.SelectionModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.TypeModel", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.SkillModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.PortfolioProfile", "PortfolioProfile")
                        .WithMany()
                        .HasForeignKey("PortfolioProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.SelectionModel", "SkillLevel")
                        .WithMany()
                        .HasForeignKey("SkillLevelId");

                    b.Navigation("PortfolioProfile");

                    b.Navigation("SkillLevel");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.SpaceModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.DiaryProfile", "DiaryProfile")
                        .WithMany("SpaceModels")
                        .HasForeignKey("DiaryProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaryProfile");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.VideoModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.MediaModel", "MediaModel")
                        .WithMany("VideoModels")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.ProjectModel", null)
                        .WithMany("Videos")
                        .HasForeignKey("ProjectModelId");

                    b.Navigation("MediaModel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.CollectionModel", b =>
                {
                    b.Navigation("MediaModels");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.DiaryProfile", b =>
                {
                    b.Navigation("SpaceModels");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.MediaModel", b =>
                {
                    b.Navigation("ConditionModel");

                    b.Navigation("PhotoModels");

                    b.Navigation("VideoModels");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ProjectModel", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.SpaceModel", b =>
                {
                    b.Navigation("MediaModels");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.UserModel", b =>
                {
                    b.Navigation("DiaryProfile");

                    b.Navigation("PortfolioProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
